apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: newsman
          artifact-id: b251a924-606a-4cd2-b703-056fa7bd56b8
          target-environment: env1
